export const COLORS = {
  white: "#ffffff",
  black: "#000000",
  lightGrey: "#B3B4B6",
  accent: "#FFC231",
  accentRed: "#FB5D2E",
  accentPink: "#F96165",
};

export const categories = [
  {
    name: "Burger",
    image: require("../../assets/burger.png"),
    items: [
      {
        name: "Classic Burger",
        weight: 120,
        rating: 5.0,
        price: 199,
        isTopOfTheWeek: true,
        image: require("../../assets/alootikkiburger.png"),
        size: 'Large 12"',
        crust: "Thick Crust",
        delivery: 20,
        ingredients: [
          require("../../assets/flour.png"),
          require("../../assets/cheese.png"),
          require("../../assets/Sliced-Onion.png"),
          require("../../assets/Tomato.png"),
        ],
      },
      {
        name: "Alo Tikki Burger",
        weight: 150,
        rating: 4.5,
        price: 299,
        isTopOfTheWeek: true,
        image: require("../../assets/alootikkiburger.png"),
        size: 'Large 12"',
        crust: "Thick Crust",
        delivery: 20,
        ingredients: [
          require("../../assets/flour.png"),
          require("../../assets/cheese.png"),
          require("../../assets/Sliced-Onion.png"),
          require("../../assets/Tomato.png"),
        ],
      },
      {
        name: "Biggie Cheese",
        weight: 250,
        rating: 4.2,
        price: 299,
        isTopOfTheWeek: true,
        image: require("../../assets/biggiecheese.png"),
        size: 'Large 12"',
        crust: "Thick Crust",
        delivery: 50,
        ingredients: [
          require("../../assets/flour.png"),
          require("../../assets/cheese.png"),
          require("../../assets/Sliced-Onion.png"),
          require("../../assets/Tomato.png"),
        ],
      },
      {
        name: "Plain Cheese Pizza",
        weight: 450,
        rating: 4.6,
        price: 299,
        isTopOfTheWeek: true,
        image: require("../../assets/alootikkiburger.PNG"),
        size: 'Large 12"',
        crust: "Thin Crust",
        delivery: 0,
        ingredients: [
          require("../../assets/flour.png"),
          require("../../assets/cheese.png"),
          require("../../assets/Sliced-Onion.png"),
          require("../../assets/Tomato.png"),
        ],
      },
    ],
  },
  {
    name: "Mexican Pizza",
    weight: 450,
    rating: 4.6,
    price: 299,
    isTopOfTheWeek: true,
    image: require("../../database/images/burger/mexicangreerwave.png"),
    size: 'Large 12"',
    crust: "Thin Crust",
    delivery: 0,
    ingredients: [
      require("../../assets/flour.png"),
      require("../../assets/cheese.png"),
      require("../../assets/Sliced-Onion.png"),
      require("../../assets/Tomato.png"),
    ],
  },
  {
    name: "Soft Drink",
    image: require("../database/images/softdrink.png"),
    items: [
      {
        name: "Coca Cola",
        weight: 200,
        rating: 5.0,
        price: 299,
        isTopOfTheWeek: true,
        image: require("../../assets/cocacola.png"),
        size: "Medium Glass",
        crust: "Small",
        delivery: 10,
        ingredients: [require("../../assets/cocacola.png")],
      },
      {
        name: "Orange Juice",
        weight: 2500,
        rating: 4.5,
        price: 199,
        isTopOfTheWeek:true,
        image: require("../../assets/orange.png"),
        size: "Large Glass",
        crust: "Large Ice",
        delivery: 8,
        ingredients: [require("../../assets/orange.png")],
      },
      {
        name: "Mango Juice",
        weight: 150,
        rating: 5.0,
        price: 99,
        isTopOfTheWeek: true,
        image: require("../../assets/mango.png"),
        size: "Large Glass",
        crust: "Small Ice",
        delivery: 5,
        ingredients: [require("../../assets/mango.png")],
      },
    ],
  },
];
